import React from "react";


const tabPop = [
    {
      src: require("../../img/PierreLapointeEnnui.jpg"),
      alt: "Pierre Lapointe",
      title: "Pierre Lapointe",
      artiste: "Pierre Lapointe",
      titrealbum: "Pour déjouer l'ennui",
      chanson1: "Tatouage",
      chanson2: "La plus belle des maisons",
      chanson3: "Pour déjouer l'ennui",
      chanson4: "Un coeur qui saigne",
      chanson5: "Le monarque des indes",
      chanson6: "Amour bohème",
      chanson7: "Amour ou songe",
      chanson8: "Dis-moi je ne sais pas",
      chanson9: "Je connais le chemin",
      chanson10: "Vivre ma peine",
      chanson11: "Qu'est ce qu'on y peut",
      chanson12: "Vendredi 13",
    },
    {
      src: require("../../img/PierreLapointePunkt.jpg"),
      alt: "Pierre Lapointe",
      title: "Pierre Lapointe",
      artiste: "Pierre Lapointe",
      titrealbum: "Punkt",
      chanson1: "Tatouage",
      chanson2: "La plus belle des maisons",
      chanson3: "Pour déjouer l'ennui",
      chanson4: "Un coeur qui saigne",
      chanson5: "Le monarque des indes",
      chanson6: "Amour bohème",
      chanson7: "Amour ou songe",
      chanson8: "Dis-moi je ne sais pas",
      chanson9: "Je connais le chemin",
      chanson10: "Vivre ma peine",
      chanson11: "Qu'est ce qu'on y peut",
      chanson12: "Vendredi 13",
    },
    {
      src: require("../../img/PierreLapointeScienceCoeur.jpg"),
      alt: "Pierre Lapointe",
      title: "Pierre Lapointe",
      artiste: "Pierre Lapointe",
      titrealbum: "La science du coeur",
      chanson1: "Tatouage",
      chanson2: "La plus belle des maisons",
      chanson3: "Pour déjouer l'ennui",
      chanson4: "Un coeur qui saigne",
      chanson5: "Le monarque des indes",
      chanson6: "Amour bohème",
      chanson7: "Amour ou songe",
      chanson8: "Dis-moi je ne sais pas",
      chanson9: "Je connais le chemin",
      chanson10: "Vivre ma peine",
      chanson11: "Qu'est ce qu'on y peut",
      chanson12: "Vendredi 13",
    },
    {
      src: require("../../img/PierreLapointeForetDesMalAimes.jpg"),
      alt: "Pierre Lapointe",
      title: "Pierre Lapointe",
      artiste: "Pierre Lapointe",
      titrealbum: "La foret des mal aimés",
      chanson1: "Tatouage",
      chanson2: "La plus belle des maisons",
      chanson3: "Pour déjouer l'ennui",
      chanson4: "Un coeur qui saigne",
      chanson5: "Le monarque des indes",
      chanson6: "Amour bohème",
      chanson7: "Amour ou songe",
      chanson8: "Dis-moi je ne sais pas",
      chanson9: "Je connais le chemin",
      chanson10: "Vivre ma peine",
      chanson11: "Qu'est ce qu'on y peut",
      chanson12: "Vendredi 13",
    },
    ];
  
    const tabBlues = [
      {
        src: require("../../img/SRVBluesYouCanUse.jpg"),
        alt: "SRV",
        title: "SRV",
        artiste: "Stevie Ray Vaughan",
        titrealbum: "Blues you can use",
        chanson1: "Tatouage",
        chanson2: "La plus belle des maisons",
        chanson3: "Pour déjouer l'ennui",
        chanson4: "Un coeur qui saigne",
        chanson5: "Le monarque des indes",
        chanson6: "Amour bohème",
        chanson7: "Amour ou songe",
        chanson8: "Dis-moi je ne sais pas",
        chanson9: "Je connais le chemin",
        chanson10: "Vivre ma peine",
        chanson11: "Qu'est ce qu'on y peut",
        chanson12: "Vendredi 13",
      },
      {
        src: require("../../img/SRVStandTheWeather.jpg"),
        alt: "SRV",
        title: "SRV",
        artiste: "Stevie Ray Vaughan",
        titrealbum: "Couldn't stand the weather",
        chanson1: "Tatouage",
        chanson2: "La plus belle des maisons",
        chanson3: "Pour déjouer l'ennui",
        chanson4: "Un coeur qui saigne",
        chanson5: "Le monarque des indes",
        chanson6: "Amour bohème",
        chanson7: "Amour ou songe",
        chanson8: "Dis-moi je ne sais pas",
        chanson9: "Je connais le chemin",
        chanson10: "Vivre ma peine",
        chanson11: "Qu'est ce qu'on y peut",
        chanson12: "Vendredi 13",
      },
      {
        src: require("../../img/SRVTexasFlood.jpg"),
        alt: "SRV",
        title: "SRV",
        artiste: "Stevie Ray Vaughan",
        titrealbum: "Texas Flood",
        chanson1: "Tatouage",
        chanson2: "La plus belle des maisons",
        chanson3: "Pour déjouer l'ennui",
        chanson4: "Un coeur qui saigne",
        chanson5: "Le monarque des indes",
        chanson6: "Amour bohème",
        chanson7: "Amour ou songe",
        chanson8: "Dis-moi je ne sais pas",
        chanson9: "Je connais le chemin",
        chanson10: "Vivre ma peine",
        chanson11: "Qu'est ce qu'on y peut",
        chanson12: "Vendredi 13",
      },
      {
        src: require("../../img/SRVCompleteEpicRecordings.jpg"),
        alt: "SRV",
        title: "SRV",
        artiste: "Stevie Ray Vaughan",
        titrealbum: "The complete epic recordings collection",
        chanson1: "Tatouage",
        chanson2: "La plus belle des maisons",
        chanson3: "Pour déjouer l'ennui",
        chanson4: "Un coeur qui saigne",
        chanson5: "Le monarque des indes",
        chanson6: "Amour bohème",
        chanson7: "Amour ou songe",
        chanson8: "Dis-moi je ne sais pas",
        chanson9: "Je connais le chemin",
        chanson10: "Vivre ma peine",
        chanson11: "Qu'est ce qu'on y peut",
        chanson12: "Vendredi 13",
      },
      ];  

 

    export class Chansons extends React.Component {  
        
      
        render() {  
            return (  
                    <h1>Chansons!</h1>
                    )
                };
            }